Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.8/dist-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd

data_cols = ["Number","Recommendation","Audit Question","Weight","Level","Description","Grade"]
datas = pd.read_csv("data/manufactoring_on_board.csv", header=0, names=data_cols, na_filter=False)

print(datas.Level[1])
datas
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[1;32m      3[0m data_cols [38;5;241m=[39m [[38;5;124m"[39m[38;5;124mNumber[39m[38;5;124m"[39m,[38;5;124m"[39m[38;5;124mRecommendation[39m[38;5;124m"[39m,[38;5;124m"[39m[38;5;124mAudit Question[39m[38;5;124m"[39m,[38;5;124m"[39m[38;5;124mWeight[39m[38;5;124m"[39m,[38;5;124m"[39m[38;5;124mLevel[39m[38;5;124m"[39m,[38;5;124m"[39m[38;5;124mDescription[39m[38;5;124m"[39m,[38;5;124m"[39m[38;5;124mGrade[39m[38;5;124m"[39m]
[1;32m      4[0m datas [38;5;241m=[39m pd[38;5;241m.[39mread_csv([38;5;124m"[39m[38;5;124mdata/manufactoring_on_board.csv[39m[38;5;124m"[39m, header[38;5;241m=[39m[38;5;241m0[39m, names[38;5;241m=[39mdata_cols, na_filter[38;5;241m=[39m[38;5;28;01mFalse[39;00m)

[0;31mModuleNotFoundError[0m: No module named 'pandas'
ModuleNotFoundError: No module named 'pandas'

